name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release name (will be used as Julia version, e.g., 1.11, 1.10, 1.9)'
        required: true
        default: '1.11'
        type: string
      release_tag:
        description: 'Git tag for the release (e.g., v1.11.0)'
        required: true
        default: 'v1.11.0'
        type: string

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        sysimage-type: [combined]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      
    - name: Setup Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: ${{ github.event.inputs.release_name }}
        
    - name: Cache Julia packages
      uses: actions/cache@v4
      env:
        cache-name: cache-julia-packages
      with:
        path: ~/.julia/packages
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-
          
    - name: Install dependencies
      run: |
        julia --project=. -e 'using Pkg; Pkg.instantiate()'
        
    - name: Build sysimage
      run: |
        julia --project=. build_all_sysimages.jl
        
    - name: Upload sysimage artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-julia-${{ github.event.inputs.release_name }}
        path: default_sysimage.*
        retention-days: 90

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      
    - name: Download all artifacts
      uses: actions/download-artifact@v5
      
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.release_tag }}
        name: Julia ${{ github.event.inputs.release_name }} Sysimages
        body: |
          Julia Sysimages Release
          
          This release contains pre-built Julia sysimages for Julia ${{ github.event.inputs.release_name }}:
          - Combined use case (LanguageServer.jl + SymbolServer + Plots)
          
          Built for:
          - Windows
          - macOS  
          - Linux
          
          Julia version: ${{ github.event.inputs.release_name }}
        draft: false
        prerelease: false
        files: |
          ubuntu-latest-julia-${{ github.event.inputs.release_name }}/*
          windows-latest-julia-${{ github.event.inputs.release_name }}/*
          macos-latest-julia-${{ github.event.inputs.release_name }}/*
